included:
  - Sources
  - Tests

excluded:
  - .build
  - .swiftpm
  - Packages
  - .git
  - DerivedData
  - "**/Generated"
  - "**/Resources"

opt_in_rules:
  - array_init
  - closure_spacing
  - contains_over_first_not_nil
  - empty_count
  - empty_string
  - explicit_init
  - fallthrough
  - fatal_error_message
  - first_where
  - joined_default_parameter
  - last_where
  - literal_expression_end_indentation
  - multiline_arguments
  - multiline_parameters
  - operator_usage_whitespace
  - overridden_super_call
  - private_outlet
  - redundant_nil_coalescing
  - sorted_first_last
  - switch_case_alignment
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call

disabled_rules:
  - explicit_self
  - identifier_name
  - file_header
  - explicit_acl
  - explicit_top_level_acl
  - explicit_type_interface
  - missing_docs
  - required_deinit
  - trailing_whitespace
  - trailing_newline
  - trailing_comma
  - vertical_whitespace
  - indentation_width
  - sorted_imports
  - file_name

force_cast: warning
force_try: warning

line_length:
  warning: 120
  error: 140
  ignores_comments: true
  ignores_urls: true

file_length:
  warning: 450
  error: 500
  ignore_comment_only_lines: true

type_body_length:
  warning: 250
  error: 400

function_body_length:
  warning: 80
  error: 120

cyclomatic_complexity:
  warning: 15
  error: 25

nesting:
  type_level:
    warning: 4
    error: 6
  function_level:
    warning: 5
    error: 7

large_tuple:
  warning: 4
  error: 5

reporter: "xcode"
